### ISSUE TITLE
Matplotlib/plotting should be an optional dependency?

### ISSUE THREAD

**Issue by amogorkon** [Python-Fuzzylogic/fuzzylogic#10]

**Comment by Averyyun** [comment]
Yes, I also wish this plotting could be optional, which would be more efficient and save memory, especially if you're running code a lot of times at once.

**Comment by amogorkon** [comment]
Okay, with the next release `py -m pip install fuzzylogic[plotting]` should work and raise an ImportError when trying to plot without matplotlib available.
