### ISSUE TITLE
Showcase code not generating plot

### ISSUE THREAD

**Issue by BorelHendrake** [Python-Fuzzylogic/fuzzylogic#53]
Using the following code does not generate the expected plot as shown in the showcase documentation:

from matplotlib import pyplot
from fuzzylogic.classes import Domain
from fuzzylogic.functions import R, S, alpha

pyplot.rc("figure", figsize=(10, 10))

T = Domain("test", 0, 30, res=0.1)

T.up = R(1,10)

T.up.plot()

I am using python3.   The code runs without any apparent error or issues.   However, no plot is generated.   I placed additonal code after the T.up.plot() to pause the program and still no plot output.

Any suggestions for generating the plot files as expected?

Thank you very much

**Comment by amogorkon** [comment]
How do you run the code?

I just tried to run the code in Thonny, where it behaved pretty much like you described, but when I run it in a Jupyter Notebook in vscode, it runs as expected.

**Comment by amogorkon** [comment]
```
from matplotlib import pyplot
from fuzzylogic.classes import Domain
from fuzzylogic.functions import R, S, alpha

pyplot.rc("figure", figsize=(10,10))
T = Domain("test", 0, 30, res=0.1)
T.up = R(1,10)
T.up.plot()
**pyplot.savefig('foo.png')**
```
should work either way. Closing the issue as solved.

**Comment by BorelHendrake** [comment]
Plot is correctly save to file.

Thank you very much for the support.
