### ISSUE TITLE
Showcase inference example does not print results

### ISSUE THREAD

**Issue by BorelHendrake** [Python-Fuzzylogic/fuzzylogic#54]
The example in the showcase for inference:

from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very
from fuzzylogic.functions import R, S

temp = Domain("Temperature", -80, 80)
hum = Domain("Humidity", 0, 100)
motor = Domain("Speed", 0, 2000)

temp.cold = S(0,20)
temp.hot = R(15,30)

hum.dry = S(20,50)
hum.wet = R(40,70)

motor.fast = R(1000,1500)
motor.slow = ~motor.fast

R1 = Rule({(temp.hot, hum.dry): motor.fast})
R2 = Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = Rule({(temp.cold, hum.wet): motor.slow})

rules = Rule({(temp.hot, hum.dry): motor.fast,
              (temp.cold, hum.dry): very(motor.slow),
              (temp.hot, hum.wet): very(motor.fast),
              (temp.cold, hum.wet): motor.slow,
             })

rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

values = {hum: 45, temp: 22}
print(R1(values), R2(values), R3(values), R4(values), "=>", rules(values))

The print does not output the given values.   Instead, it outputs the following:
    print( R1( values ), R2( values ), R3( values ), R4( values ), "=>", rules( values ) )
           ^^^^^^^^^^^^
  File "C:\Users\mysixa\AppData\Local\Programs\Python\Python312\Lib\site-packages\fuzzylogic\classes.py", line 447, in __call__
    index = sum(v.center_of_gravity * x for v, x in weights) / sum(x for v, x in weights)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mysixa\AppData\Local\Programs\Python\Python312\Lib\site-packages\fuzzylogic\classes.py", line 447, in <genexpr>
    index = sum(v.center_of_gravity * x for v, x in weights) / sum(x for v, x in weights)
                ~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for *: 'method' and 'float'

Is there a correction to the example which will correctly output the values as expected in this example?

Thank you very much

**Comment by amogorkon** [comment]
Ah, yes. Sorry about that. The bug is already fixed, but I didn't release it yet. There is a () missing. You can put it in yourself - it's supposed to be `v.center_of_gravity()`

**Comment by BorelHendrake** [comment]
That fixed it nicely.

Thank you very much

**Comment by amogorkon** [comment]
Oh. How embarassing. I used that to debug when I refactored the defuzzification. Just search for `print('ohalala')` and delete it. There is no instance of that in my current code, so it will be gone in the next release.
